const videoPrompts = {
    gesture: {
        hello: "Create a clear and easy-to-understand educational video animation from this image. The person should slowly raise one hand and gently wave hello twice. The hand movement should be large and clearly visible for nonverbal learning. Keep the head, shoulders, and torso completely still. Add a friendly facial expression with a soft smile. Smooth motion, stable camera, no distortion, preserve identity, simple background, high quality.",
        no_hand: "Create a clear and easy-to-understand educational animation from this image. The person should slowly and clearly shake their head left and right to indicate a strong \"no\". The movement should be slightly exaggerated but realistic and repeated twice for clarity. Add a serious facial expression showing disapproval. Optionally raise one hand in a gentle stop gesture. Smooth motion, stable background, no distortion, preserve identity, high quality.",
        no_head: "Create a clear and easy-to-understand video animation from this image. The person should slowly and clearly shake their head left and right to indicate \"no\". The movement should be exaggerated but realistic and repeated twice. Head movement only — no hand movement, no body movement. Keep shoulders and torso completely still. Slightly serious facial expression. Smooth motion, stable camera, no distortion, preserve identity, high quality.",
        yes: "Create a clear educational video animation from this image. The person should slowly nod their head up and down to indicate \"yes\". The movement should be slightly exaggerated but realistic and repeated twice for clarity. Head movement only — no hand or body movement. Keep shoulders and background completely still. Add a gentle positive facial expression. Smooth motion, stable camera, no distortion, preserve identity, high quality.",
        goodbye: "Educational style animation. The person slowly raises one hand and clearly waves goodbye twice. Large, visible hand movement at slow speed for clear nonverbal communication. Keep the head, shoulders, and torso completely still. No distortion, stable background, high clarity, smooth motion.",
        pointing: "Educational animation. The person slowly raises their dominant hand and points directly at the camera/viewer. The movement should be slow and deliberate for clear nonverbal learning. Keep the torso and background completely still. Smooth motion, high quality.",
        clapping: "Friendly educational animation. The person brings their hands together to clap slowly and clearly three times. Large, visible hand movements. Add a joyful facial expression with a soft smile. Stable camera, preserve identity.",
        hugging: "Warm educational animation. The person opens their arms wide in a gentle hugging gesture towards the camera. The movement should be slow, inviting, and calm. Keep the background simple and stable. High quality, no distortion.",
        quiet: "Educational animation for 'shhh'. The person slowly raises one index finger and places it vertically over their closed lips. The head tilt should be slight and the expression should be calm and serious. Smooth motion, stable background.",
        listening: "Educational animation for 'listening'. The person slowly cups one hand behind their ear and tilts their head slightly towards that side. Encouraging and attentive facial expression. Keep movement localized to the hand and head. High clarity.",
    },
    emotion: {
        sad: "Create a clear emotional educational animation from this image. The person should show a clear sad facial expression: slightly lowered head, downturned mouth, and soft eyes. No head movement, no hand movement, no body movement. Only facial expression change. Keep the background stable and simple. Smooth transition, no distortion, preserve identity, high quality.",
        happy: "Create a clear educational emotional animation from this image. The person should show a bright happy facial expression with a natural smile and slightly raised cheeks. Keep head, shoulders, and torso completely still. No hand movement. Smooth and natural facial expression change. Stable camera, no distortion, preserve identity, high quality.",
        angry: "Create a clear educational emotional animation from this image. The person should show a clear angry facial expression: slightly lowered eyebrows, firm lips, and intense eyes. No head movement, no hand movement, no body movement. Only facial expression change. Keep background stable and simple. Smooth motion, no distortion, preserve identity, high quality.",
        surprised: "Create a clear educational emotional animation. The person's eyes should widen softly and their eyebrows should raise. The mouth can be slightly open in a gentle 'O' shape. No sudden or jerky movements. Keep the body still. Smooth transition, high quality.",
        scared: "Create a clear educational emotional animation. The person shows a worried expression with slightly furrowed brows and wider eyes. Shoulders can tense slightly but keep the head and torso mostly still. Smooth transition, preserve identity.",
        tired: "Create a clear educational animation. The person shows a sleepy expression with heavy eyelids and a slow, gentle yawn. Keep the background simple and stable. No distortion, high quality.",
    },
    recognition: {
        object: "Create a clear educational video of the object: [OBJECT_NAME]. Show it from a friendly perspective, rotating slightly to reveal its shape and features. Keep the background clean and professional. 5-second smooth animation.",
        person: "Create a friendly greeting animation for [PERSON_NAME]. The person should look at the camera with a gentle smile and a slight, slow nod of recognition. Preserve identity, stable background, high clarity.",
    }
};

module.exports = videoPrompts;
